name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ gr033 }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email gr033@kyonggi.ac.kr
          git add -A .
          git commit -m "generated"
          git push
